
title: Handpoint
email: support@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Handpoint - Go mobile | Go global
twitter_username: jekyllrb
github_username:  jekyll
permalink: pretty

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
